# Autogenerated wrapper script for TVMFFI_jll for armv6l-linux-gnueabihf-cxx11
export libtvm_ffi, libtvm_ffi_testing

JLLWrappers.@generate_wrapper_header("TVMFFI")
JLLWrappers.@declare_library_product(libtvm_ffi, "libtvm_ffi.so")
JLLWrappers.@declare_library_product(libtvm_ffi_testing, "libtvm_ffi_testing.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtvm_ffi,
        "lib/libtvm_ffi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtvm_ffi_testing,
        "lib/libtvm_ffi_testing.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
