# Autogenerated wrapper script for TVMFFI_jll for x86_64-apple-darwin
export libtvm_ffi, libtvm_ffi_testing

JLLWrappers.@generate_wrapper_header("TVMFFI")
JLLWrappers.@declare_library_product(libtvm_ffi, "@rpath/libtvm_ffi.dylib")
JLLWrappers.@declare_library_product(libtvm_ffi_testing, "@rpath/libtvm_ffi_testing.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtvm_ffi,
        "lib/libtvm_ffi.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtvm_ffi_testing,
        "lib/libtvm_ffi_testing.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
